# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1.xci
# IP: The module: 'design_microblaze_flash_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_flash_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_flash_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1.xci
# IP: The module: 'design_microblaze_flash_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_flash_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jose/Xilinx/Vivado-Projects/class5-Microblaze-booting-from-qspi-flash/class5-Microblaze-booting-from-qspi-flash.srcs/sources_1/bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_flash_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
