# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_microblaze/design_microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze || ORIG_REF_NAME==design_microblaze} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_microblaze_0_0/design_microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_microblaze_0_0 || ORIG_REF_NAME==design_microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_dlmb_v10_0/design_microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_dlmb_v10_0 || ORIG_REF_NAME==design_microblaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_ilmb_v10_0/design_microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_ilmb_v10_0 || ORIG_REF_NAME==design_microblaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_dlmb_bram_if_cntlr_0/design_microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_microblaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_ilmb_bram_if_cntlr_0/design_microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_microblaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_lmb_bram_0/design_microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_lmb_bram_0 || ORIG_REF_NAME==design_microblaze_lmb_bram_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_xbar_0/design_microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_xbar_0 || ORIG_REF_NAME==design_microblaze_xbar_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_microblaze_0_axi_periph_0/design_microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_microblaze_0_axi_intc_0/design_microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_microblaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_microblaze_0_xlconcat_0/design_microblaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_microblaze_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_mdm_1_0/design_microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_mdm_1_0 || ORIG_REF_NAME==design_microblaze_mdm_1_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_clk_wiz_1_0/design_microblaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_clk_wiz_1_0 || ORIG_REF_NAME==design_microblaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_rst_clk_wiz_1_100M_0/design_microblaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_microblaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_axi_uartlite_0_0/design_microblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==design_microblaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_microblaze/ip/design_microblaze_axi_timer_0_0/design_microblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_axi_timer_0_0 || ORIG_REF_NAME==design_microblaze_axi_timer_0_0} -quiet] -quiet

# XDC: bd/design_microblaze/design_microblaze_ooc.xdc
