# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jose/Xilinx/Vivado-Projects/freertos-helloworld/freertos-helloworld.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_lmb_bram_0/design_microblaze_lmb_bram_0.xci
# IP: The module: 'design_microblaze_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jose/Xilinx/Vivado-Projects/freertos-helloworld/freertos-helloworld.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_lmb_bram_0/design_microblaze_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jose/Xilinx/Vivado-Projects/freertos-helloworld/freertos-helloworld.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_lmb_bram_0/design_microblaze_lmb_bram_0.xci
# IP: The module: 'design_microblaze_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jose/Xilinx/Vivado-Projects/freertos-helloworld/freertos-helloworld.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_lmb_bram_0/design_microblaze_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
