# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/bitstream-boot-flash.xdc

# Block Designs: bd/design_microblaze_flash/design_microblaze_flash.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash || ORIG_REF_NAME==design_microblaze_flash} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_microblaze_0_0/design_microblaze_flash_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_microblaze_0_0 || ORIG_REF_NAME==design_microblaze_flash_microblaze_0_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_dlmb_v10_1/design_microblaze_flash_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_dlmb_v10_1 || ORIG_REF_NAME==design_microblaze_flash_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_v10_1/design_microblaze_flash_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_ilmb_v10_1 || ORIG_REF_NAME==design_microblaze_flash_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_dlmb_bram_if_cntlr_1/design_microblaze_flash_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_microblaze_flash_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_ilmb_bram_if_cntlr_1/design_microblaze_flash_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_microblaze_flash_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_lmb_bram_1/design_microblaze_flash_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_lmb_bram_1 || ORIG_REF_NAME==design_microblaze_flash_lmb_bram_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_xbar_0/design_microblaze_flash_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_xbar_0 || ORIG_REF_NAME==design_microblaze_flash_xbar_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_microblaze_0_axi_periph_0/design_microblaze_flash_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_microblaze_flash_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_microblaze_0_axi_intc_0/design_microblaze_flash_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_microblaze_flash_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_microblaze_0_xlconcat_0/design_microblaze_flash_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_microblaze_flash_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_mdm_1_1/design_microblaze_flash_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_mdm_1_1 || ORIG_REF_NAME==design_microblaze_flash_mdm_1_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_clk_wiz_1_1/design_microblaze_flash_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_clk_wiz_1_1 || ORIG_REF_NAME==design_microblaze_flash_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_rst_clk_wiz_1_100M_1/design_microblaze_flash_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_microblaze_flash_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_axi_uartlite_0_0/design_microblaze_flash_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_axi_uartlite_0_0 || ORIG_REF_NAME==design_microblaze_flash_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_axi_timer_0_1/design_microblaze_flash_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_axi_timer_0_1 || ORIG_REF_NAME==design_microblaze_flash_axi_timer_0_1} -quiet] -quiet

# IP: bd/design_microblaze_flash/ip/design_microblaze_flash_axi_quad_spi_0_0/design_microblaze_flash_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_flash_axi_quad_spi_0_0 || ORIG_REF_NAME==design_microblaze_flash_axi_quad_spi_0_0} -quiet] -quiet

# XDC: bd/design_microblaze_flash/design_microblaze_flash_ooc.xdc
